#!/usr/bin/env bash
# Bash script that displays numbers from 1 to 100
#    Prints FizzBuzz if number is multiple of 3 and 5
#    Prints Fizz for number multiple of 3
#    Prints Buzz for number multiple of 5
#    if not print the number itself

i=1
while [ $i -le 100 ]
do
    if (( $i % 3 == 0 && $i % 5 == 0 ))
    then
        echo "FizzBuzz"
    elif (( $i % 3 == 0 ))
    then
        echo "Fizz"
    elif (( $i % 5 == 0 ))
    then
        echo "Buzz"
    else
         echo "$i"
    fi
    ((i++))
done
