#!/usr/bin/env bash
# This uses case to ckeck for conditions in a loop

i=1
while [ $i -le 20 ]
do
    echo "$i"
    case $i in
    "4") echo "bad luck form China";;
    "9") echo "bad luck form Japan";;
    "17")echo "bad luck form Italy";;
    esac
    ((i++))
done 
