#!/usr/bin/env bash
# This uses more if conditions in a loop

i=1
while [ $i -le 20 ]
do
    if [ $i -eq 4 ]
    then
         echo "badluck form China"
    elif [ $i -eq 9 ]
    then
        echo "bad luck from Japan"
    elif [ $i -eq 17 ]
    then
        echo "bad luck from Italy"
    else
        echo "$i"
    fi
    ((i++))
done 
