#!/bin/bash

# Change the user directive in /etc/nginx/nginx.conf to nginx
sed -i 's/user  root;/user  nginx;/' /etc/nginx/nginx.conf

# Remove the listen directive for port 80 and add one for port 8080 in /etc/nginx/conf.d/default.conf 
sed -i 's/listen       80;/listen       8080;/g' /etc/nginx/conf.d/default.conf

# Start nginx service
nginx -g 'daemon off;'
